#if UNITY_EDITOR
using System;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.Callbacks;
using Genoverrei.Library.Attribute;
using System.Text.RegularExpressions;

namespace Genoverrei.Library.Editor
{
    internal sealed class HierarchyMenuGenerator : AssetPostprocessor
    {
        static void OnPostprocessAllAssets(
            string[] imported,
            string[] deleted,
            string[] moved,
            string[] movedFrom)
        {
            bool shouldRebuild = false;

            // ── ลบ prefab → unregister (rebuild) ──
            foreach (var path in deleted)
            {
                if (path.EndsWith(".prefab"))
                {
                    shouldRebuild = true;
                    break;
                }
            }

            // ── เพิ่ม / import prefab → register ──
            if (!shouldRebuild)
            {
                foreach (var path in imported)
                {
                    // ข้าม generated file เพื่อตัด loop
                    if (path.EndsWith(HierarchyMenuBuilder.GENERATED_FILENAME)) return;

                    if (path.EndsWith(".prefab"))
                    {
                        shouldRebuild = true;
                        break;
                    }
                }
            }

            // ── trigger แค่ครั้งเดียวต่อ batch ──
            if (shouldRebuild)
                HierarchyMenuBuilder.Build();
        }
    }

    public static class HierarchyMenuBuilder
    {
        internal const string GENERATED_FILENAME = "HierarchyMenuDefinitions.g.cs";

        [DidReloadScripts]
        static void OnReload() => Build();

        public static void Build()
        {
            // ── 1. หา Type ที่มี Attribute ──
            var markedTypes = new List<(Type type, string menuPath)>();
            foreach (var type in TypeCache.GetTypesWithAttribute<CreateHierarchyMenu>())
            {
                var attr = (CreateHierarchyMenu)
                    System.Attribute.GetCustomAttribute(type, typeof(CreateHierarchyMenu));
                markedTypes.Add((type, attr.MenuPath));
            }

            if (markedTypes.Count == 0)
            {
                WriteFile("");
                return;
            }

            // ── 2. Map type → script GUID ──
            var typeGuid = new Dictionary<Type, string>();
            foreach (var (type, _) in markedTypes)
            {
                string guid = ResolveScriptGuid(type);
                if (guid != null) typeGuid[type] = guid;
            }

            // ── 3. สแกน prefab ด้วย raw text ──
            var results = new Dictionary<Type, List<(string path, string name)>>();
            foreach (var (type, _) in markedTypes)
                results[type] = new List<(string, string)>();

            string projectRoot = Path.GetDirectoryName(Application.dataPath);

            foreach (string pGuid in AssetDatabase.FindAssets("t:Prefab"))
            {
                string assetPath = AssetDatabase.GUIDToAssetPath(pGuid);
                string fullPath = Path.Combine(projectRoot, assetPath);

                if (!File.Exists(fullPath)) continue;
                string yaml = File.ReadAllText(fullPath);

                foreach (var (type, _) in markedTypes)
                {
                    if (!typeGuid.TryGetValue(type, out string scriptGuid)) continue;
                    if (!yaml.Contains(scriptGuid)) continue;

                    string prefabName = Path.GetFileNameWithoutExtension(assetPath);
                    results[type].Add((assetPath, prefabName));
                }
            }

            // ── 4. Warning + guard ──
            bool anyEntry = false;
            foreach (var (type, _) in markedTypes)
            {
                if (results[type].Count == 0)
                    Debug.LogWarning(
                        $"[CreateHierarchyMenu] <b>{type.Name}</b> ยังไม่ได้ใส่ใน Prefab ใดๆ " +
                        "(ลาก GameObject เข้า Assets เพื่อสร้าง Prefab ก่อนนะครับ)");
                else
                    anyEntry = true;
            }

            if (!anyEntry)
            {
                WriteFile("");
                return;
            }

            // ── 5. Code generation ──
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated /> — do not edit manually");
            sb.AppendLine("using UnityEditor;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace Genoverrei.Library.Editor");
            sb.AppendLine("{");
            sb.AppendLine("    public static class HierarchyMenuDefinitions");
            sb.AppendLine("    {");

            foreach (var (type, menuPath) in markedTypes)
            {
                foreach (var (prefabAssetPath, prefabName) in results[type])
                {
                    string safeMethod = $"Spawn_{Sanitize(prefabName)}_{Guid.NewGuid():N}";

                    sb.AppendLine($"        // {type.Name} → {prefabName}");
                    sb.AppendLine($"        [MenuItem(\"GameObject/{menuPath}/{prefabName}\", false, 0)]");
                    sb.AppendLine($"        static void {safeMethod}()");
                    sb.AppendLine($"            => HierarchyMenuBuilder.Spawn(\"{prefabAssetPath}\");");
                    sb.AppendLine();
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            WriteFile(sb.ToString());
        }

        public static void Spawn(string assetPath)
        {
            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(assetPath);
            if (prefab == null)
            {
                Debug.LogError($"[CreateHierarchyMenu] หาไม่เจอ prefab ที่ path: {assetPath}");
                return;
            }

            var instance = (GameObject)PrefabUtility.InstantiatePrefab(prefab);

            if (Selection.activeGameObject != null)
                instance.transform.SetParent(Selection.activeGameObject.transform, false);

            instance.transform.localPosition = Vector3.zero;
            GameObjectUtility.EnsureUniqueNameForSibling(instance);
            Undo.RegisterCreatedObjectUndo(instance, $"Create {instance.name}");
            Selection.activeObject = instance;
        }

        static string ResolveScriptGuid(Type type)
        {
            foreach (string g in AssetDatabase.FindAssets($"{type.Name} t:MonoScript"))
            {
                string path = AssetDatabase.GUIDToAssetPath(g);
                var ms = AssetDatabase.LoadAssetAtPath<MonoScript>(path);
                if (ms?.GetClass() == type) return g;
            }
            foreach (string g in AssetDatabase.FindAssets("t:MonoScript"))
            {
                string path = AssetDatabase.GUIDToAssetPath(g);
                var ms = AssetDatabase.LoadAssetAtPath<MonoScript>(path);
                if (ms?.GetClass() == type) return g;
            }
            return null;
        }

        static string Sanitize(string s) =>
            Regex.Replace(s, @"[^a-zA-Z0-9_]", "_");

        static void WriteFile(string content)
        {
            string[] guids = AssetDatabase.FindAssets("HierarchyMenuGenerator t:Script");
            if (guids.Length == 0) return;

            string folder = Path.GetDirectoryName(AssetDatabase.GUIDToAssetPath(guids[0]));
            string filePath = Path.Combine(folder, GENERATED_FILENAME);

            if (File.Exists(filePath))
            {
                string existing = File.ReadAllText(filePath);
                if (NormalizeGuids(existing) == NormalizeGuids(content)) return;
            }

            File.WriteAllText(filePath, content);
            EditorApplication.delayCall += AssetDatabase.Refresh;
        }

        static string NormalizeGuids(string src) =>
            Regex.Replace(src, @"Spawn_[a-zA-Z0-9_]+_[a-fA-F0-9]{32}", "SPAWN_X");
    }
}
#endif