// <auto-generated /> — do not edit manually
using UnityEditor;
using UnityEngine;

namespace Genoverrei.Library.Editor
{
    public static class HierarchyMenuDefinitions
    {
        // VNSceneReader → VNSceneReader
        [MenuItem("GameObject/GenoverreiLibrary/Core/VNSceneReader", false, 0)]
        static void Spawn_VNSceneReader_8202fbdfce1846679d6b2fcd95a5ece8()
            => HierarchyMenuBuilder.Spawn("Packages/com.genoverrei.library/Runtime/Core/VN_Core/VNSceneReader.prefab");

        // EventBus → EventBus
        [MenuItem("GameObject/GenoverreiLibrary/Desig/EventBus", false, 0)]
        static void Spawn_EventBus_c4596722e1304e14ac1ffe36d4fe816b()
            => HierarchyMenuBuilder.Spawn("Packages/com.genoverrei.library/Runtime/DesignPatternCore/EventBus/EventBus.prefab");

        // ObjectPoolManager → ObjectPoolManager
        [MenuItem("GameObject/GenoverreiLibrary/DesignPattern/ObjectPoolManager", false, 0)]
        static void Spawn_ObjectPoolManager_851e7e9a660f49d9b32412e59335f9ee()
            => HierarchyMenuBuilder.Spawn("Packages/com.genoverrei.library/Runtime/DesignPatternCore/ObjectPool/ObjectPoolManager.prefab");

        // BasicInputManager → BasicInputManager
        [MenuItem("GameObject/GenoverreiLibrary/Core/BasicInputManager", false, 0)]
        static void Spawn_BasicInputManager_a607a2a4313c4550b2b8bb39b6f662b7()
            => HierarchyMenuBuilder.Spawn("Packages/com.genoverrei.library/Runtime/Core/InputCore/BasicInputManager.prefab");

        // GeneralInputManager → GeneralInputManager
        [MenuItem("GameObject/GenoverreiLibrary/Core/GeneralInputManager", false, 0)]
        static void Spawn_GeneralInputManager_02d76a303c7a4be9a4e0717b8f494793()
            => HierarchyMenuBuilder.Spawn("Packages/com.genoverrei.library/Runtime/Core/InputCore/GeneralInputManager.prefab");

    }
}
