// <auto-generated /> — do not edit manually
using UnityEditor;
using UnityEngine;

namespace Genoverrei.Library.Editor
{
    public static class HierarchyMenuDefinitions
    {
        // GeneralInputManager → GeneralInputManager
        [MenuItem("GameObject/GenoverreiLibrary/Core/GeneralInputManager", false, 0)]
        static void Spawn_GeneralInputManager_e32c5fcce7a045f2b305274440f338ba()
            => HierarchyMenuBuilder.Spawn("Packages/com.genoverrei.library/Runtime/Core/InputCore/GeneralInputManager.prefab");

        // VNSceneReader → VNSceneReader
        [MenuItem("GameObject/GenoverreiLibrary/Core/VNSceneReader", false, 0)]
        static void Spawn_VNSceneReader_e683aa45c3c9415da0d83df18eaff64d()
            => HierarchyMenuBuilder.Spawn("Packages/com.genoverrei.library/Runtime/Core/VN_Core/VNSceneReader.prefab");

        // EventBus → EventBus
        [MenuItem("GameObject/GenoverreiLibrary/DesignPattern/EventBus", false, 0)]
        static void Spawn_EventBus_5596a827e5c8456cafeff1acda0ef5d6()
            => HierarchyMenuBuilder.Spawn("Packages/com.genoverrei.library/Runtime/DesignPatternCore/EventBus/EventBus.prefab");

        // ObjectPoolManager → ObjectPoolManager
        [MenuItem("GameObject/GenoverreiLibrary/DesignPattern/ObjectPoolManager", false, 0)]
        static void Spawn_ObjectPoolManager_b9eb2f00a9044f28951937f3a9d3a45f()
            => HierarchyMenuBuilder.Spawn("Packages/com.genoverrei.library/Runtime/DesignPatternCore/ObjectPool/ObjectPoolManager.prefab");

        // BasicInputManager → BasicInputManager
        [MenuItem("GameObject/GenoverreiLibrary/Core/BasicInputManager", false, 0)]
        static void Spawn_BasicInputManager_68411ca4a61f4f939713afcd40a2e248()
            => HierarchyMenuBuilder.Spawn("Packages/com.genoverrei.library/Runtime/Core/InputCore/BasicInputManager.prefab");

    }
}
