// <auto-generated>
// Generated by HierarchyMenuGenerator — DO NOT EDIT MANUALLY.
// Regenerate via:  Tools ▸ GenoverreiLibrary ▸ Regenerate Hierarchy Menu
// </auto-generated>

#if UNITY_EDITOR
using UnityEditor;

namespace Genoverrei.Library.Editor
{
    // ReSharper disable UnusedMember.Local
    internal static class HierarchyMenuDefinitions
    {
        [MenuItem("GameObject/GenoverreiLibrary/Core/Controller/BasicSceneEffectController", false, 10)]
        static void Create_GenoverreiLibrary_Core_Controller_BasicSceneEffectController()
            => HierarchyMenuCreator.CreateFromPrefab("BasicSceneEffectController");

        [MenuItem("GameObject/GenoverreiLibrary/Core/Manager/BasicInputManager", false, 10)]
        static void Create_GenoverreiLibrary_Core_Manager_BasicInputManager()
            => HierarchyMenuCreator.CreateFromPrefab("BasicInputManager");

        [MenuItem("GameObject/GenoverreiLibrary/Core/Manager/GameManager", false, 10)]
        static void Create_GenoverreiLibrary_Core_Manager_GameManager()
            => HierarchyMenuCreator.CreateFromPrefab("GameManager");

        [MenuItem("GameObject/GenoverreiLibrary/Core/Manager/GeneralInputManager", false, 10)]
        static void Create_GenoverreiLibrary_Core_Manager_GeneralInputManager()
            => HierarchyMenuCreator.CreateFromPrefab("GeneralInputManager");

        [MenuItem("GameObject/GenoverreiLibrary/Core/Manager/TimeManager", false, 10)]
        static void Create_GenoverreiLibrary_Core_Manager_TimeManager()
            => HierarchyMenuCreator.CreateFromPrefab("TimeManager");

        [MenuItem("GameObject/GenoverreiLibrary/Core/VNSceneReader", false, 10)]
        static void Create_GenoverreiLibrary_Core_VNSceneReader()
            => HierarchyMenuCreator.CreateFromPrefab("VNSceneReader");

        [MenuItem("GameObject/GenoverreiLibrary/DesignPattern/EventBus", false, 10)]
        static void Create_GenoverreiLibrary_DesignPattern_EventBus()
            => HierarchyMenuCreator.CreateFromPrefab("EventBus");

        [MenuItem("GameObject/GenoverreiLibrary/DesignPattern/ObjectPoolManager", false, 10)]
        static void Create_GenoverreiLibrary_DesignPattern_ObjectPoolManager()
            => HierarchyMenuCreator.CreateFromPrefab("ObjectPoolManager");

    }
    // ReSharper restore UnusedMember.Local
}
#endif
