// <auto-generated>
// Generated by HierarchyMenuGenerator — DO NOT EDIT MANUALLY.
// Regenerate via:  Tools ▸ KogetsuLibrary ▸ Regenerate Hierarchy Menu
// </auto-generated>

#if UNITY_EDITOR
using UnityEditor;

namespace Kogetsu.Library.Editor
{
    // ReSharper disable UnusedMember.Local
    internal static class HierarchyMenuDefinitions
    {
        [MenuItem("GameObject/KogetsuLibrary/Core/Controller/BasicSceneEffectController", false, 10)]
        static void Create_KogetsuLibrary_Core_Controller_BasicSceneEffectController()
            => HierarchyMenuCreator.CreateFromPrefab("BasicSceneEffectController");

        [MenuItem("GameObject/KogetsuLibrary/Core/Manager/BasicInputManager", false, 10)]
        static void Create_KogetsuLibrary_Core_Manager_BasicInputManager()
            => HierarchyMenuCreator.CreateFromPrefab("BasicInputManager");

        [MenuItem("GameObject/KogetsuLibrary/Core/Manager/GameManager", false, 10)]
        static void Create_KogetsuLibrary_Core_Manager_GameManager()
            => HierarchyMenuCreator.CreateFromPrefab("GameManager");

        [MenuItem("GameObject/KogetsuLibrary/Core/Manager/GeneralInputManager", false, 10)]
        static void Create_KogetsuLibrary_Core_Manager_GeneralInputManager()
            => HierarchyMenuCreator.CreateFromPrefab("GeneralInputManager");

        [MenuItem("GameObject/KogetsuLibrary/Core/Manager/TimeManager", false, 10)]
        static void Create_KogetsuLibrary_Core_Manager_TimeManager()
            => HierarchyMenuCreator.CreateFromPrefab("TimeManager");

        [MenuItem("GameObject/KogetsuLibrary/Core/VNSceneReader", false, 10)]
        static void Create_KogetsuLibrary_Core_VNSceneReader()
            => HierarchyMenuCreator.CreateFromPrefab("VNSceneReader");

        [MenuItem("GameObject/KogetsuLibrary/DesignPattern/EventBus", false, 10)]
        static void Create_KogetsuLibrary_DesignPattern_EventBus()
            => HierarchyMenuCreator.CreateFromPrefab("EventBus");

        [MenuItem("GameObject/KogetsuLibrary/DesignPattern/ObjectPoolManager", false, 10)]
        static void Create_KogetsuLibrary_DesignPattern_ObjectPoolManager()
            => HierarchyMenuCreator.CreateFromPrefab("ObjectPoolManager");

    }
    // ReSharper restore UnusedMember.Local
}
#endif
